-- SQL Server 2022 语法
IF OBJECT_ID('USER_DATA', 'U') IS NOT NULL
    DROP TABLE USER_DATA;
GO

CREATE TABLE USER_DATA (
    ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NAME NVARCHAR(100),
    EMAIL NVARCHAR(100)
);
GO
