-- =============================================
-- 创建 Spring Batch 系统表（DDL）
-- =============================================

USE BatchWeaverDB;
GO

PRINT 'Creating Spring Batch metadata tables...';
GO

-- 删除现有表（按依赖关系逆序删除）
IF OBJECT_ID('BATCH_STEP_EXECUTION_CONTEXT', 'U') IS NOT NULL
    DROP TABLE BATCH_STEP_EXECUTION_CONTEXT;
GO

IF OBJECT_ID('BATCH_JOB_EXECUTION_CONTEXT', 'U') IS NOT NULL
    DROP TABLE BATCH_JOB_EXECUTION_CONTEXT;
GO

IF OBJECT_ID('BATCH_STEP_EXECUTION', 'U') IS NOT NULL
    DROP TABLE BATCH_STEP_EXECUTION;
GO

IF OBJECT_ID('BATCH_JOB_EXECUTION_PARAMS', 'U') IS NOT NULL
    DROP TABLE BATCH_JOB_EXECUTION_PARAMS;
GO

IF OBJECT_ID('BATCH_JOB_EXECUTION', 'U') IS NOT NULL
    DROP TABLE BATCH_JOB_EXECUTION;
GO

IF OBJECT_ID('BATCH_JOB_INSTANCE', 'U') IS NOT NULL
    DROP TABLE BATCH_JOB_INSTANCE;
GO

-- 1. BATCH_JOB_INSTANCE
-- 存储 Job 实例信息
CREATE TABLE BATCH_JOB_INSTANCE (
    JOB_INSTANCE_ID BIGINT IDENTITY(1,1) NOT NULL,
    VERSION BIGINT,
    JOB_NAME NVARCHAR(100) NOT NULL,
    JOB_KEY NVARCHAR(32) NOT NULL,
    CONSTRAINT PK_BATCH_JOB_INSTANCE PRIMARY KEY (JOB_INSTANCE_ID)
);
GO

CREATE UNIQUE INDEX JOB_INST_UN ON BATCH_JOB_INSTANCE (JOB_NAME, JOB_KEY);
GO

PRINT 'Table BATCH_JOB_INSTANCE created.';
GO

-- 2. BATCH_JOB_EXECUTION
-- 存储 Job 执行记录
CREATE TABLE BATCH_JOB_EXECUTION (
    JOB_EXECUTION_ID BIGINT IDENTITY(1,1) NOT NULL,
    VERSION BIGINT,
    JOB_INSTANCE_ID BIGINT NOT NULL,
    CREATE_TIME DATETIME2 NOT NULL,
    START_TIME DATETIME2,
    END_TIME DATETIME2,
    STATUS NVARCHAR(10),
    EXIT_CODE NVARCHAR(2500),
    EXIT_MESSAGE NVARCHAR(2500),
    LAST_UPDATED DATETIME2,
    CONSTRAINT PK_BATCH_JOB_EXECUTION PRIMARY KEY (JOB_EXECUTION_ID)
);
GO

ALTER TABLE BATCH_JOB_EXECUTION 
ADD CONSTRAINT JOB_INST_EXEC_FK 
FOREIGN KEY (JOB_INSTANCE_ID) 
REFERENCES BATCH_JOB_INSTANCE(JOB_INSTANCE_ID);
GO

PRINT 'Table BATCH_JOB_EXECUTION created.';
GO

-- 3. BATCH_JOB_EXECUTION_PARAMS
-- 存储 Job 执行参数
CREATE TABLE BATCH_JOB_EXECUTION_PARAMS (
    JOB_EXECUTION_ID BIGINT NOT NULL,
    PARAMETER_NAME NVARCHAR(100) NOT NULL,
    PARAMETER_TYPE NVARCHAR(100) NOT NULL,
    PARAMETER_VALUE NVARCHAR(2500),
    IDENTIFYING CHAR(1) NOT NULL,
    CONSTRAINT JOB_EXEC_PARAMS_FK 
    FOREIGN KEY (JOB_EXECUTION_ID) 
    REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);
GO

PRINT 'Table BATCH_JOB_EXECUTION_PARAMS created.';
GO

-- 4. BATCH_STEP_EXECUTION
-- 存储 Step 执行记录
CREATE TABLE BATCH_STEP_EXECUTION (
    STEP_EXECUTION_ID BIGINT IDENTITY(1,1) NOT NULL,
    VERSION BIGINT NOT NULL,
    STEP_NAME NVARCHAR(100) NOT NULL,
    JOB_EXECUTION_ID BIGINT NOT NULL,
    CREATE_TIME DATETIME2 NOT NULL,
    START_TIME DATETIME2,
    END_TIME DATETIME2,
    STATUS NVARCHAR(10),
    COMMIT_COUNT BIGINT,
    READ_COUNT BIGINT,
    FILTER_COUNT BIGINT,
    WRITE_COUNT BIGINT,
    READ_SKIP_COUNT BIGINT,
    WRITE_SKIP_COUNT BIGINT,
    PROCESS_SKIP_COUNT BIGINT,
    ROLLBACK_COUNT BIGINT,
    EXIT_CODE NVARCHAR(2500),
    EXIT_MESSAGE NVARCHAR(2500),
    LAST_UPDATED DATETIME2,
    CONSTRAINT PK_BATCH_STEP_EXECUTION PRIMARY KEY (STEP_EXECUTION_ID)
);
GO

ALTER TABLE BATCH_STEP_EXECUTION 
ADD CONSTRAINT JOB_EXEC_STEP_FK 
FOREIGN KEY (JOB_EXECUTION_ID) 
REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID);
GO

PRINT 'Table BATCH_STEP_EXECUTION created.';
GO

-- 5. BATCH_JOB_EXECUTION_CONTEXT
-- 存储 Job 执行上下文
CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT (
    JOB_EXECUTION_ID BIGINT NOT NULL,
    SHORT_CONTEXT NVARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT NVARCHAR(MAX),
    CONSTRAINT PK_BATCH_JOB_EXECUTION_CONTEXT PRIMARY KEY (JOB_EXECUTION_ID)
);
GO

ALTER TABLE BATCH_JOB_EXECUTION_CONTEXT 
ADD CONSTRAINT JOB_EXEC_CTX_FK 
FOREIGN KEY (JOB_EXECUTION_ID) 
REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID);
GO

PRINT 'Table BATCH_JOB_EXECUTION_CONTEXT created.';
GO

-- 6. BATCH_STEP_EXECUTION_CONTEXT
-- 存储 Step 执行上下文
CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT (
    STEP_EXECUTION_ID BIGINT NOT NULL,
    SHORT_CONTEXT NVARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT NVARCHAR(MAX),
    CONSTRAINT PK_BATCH_STEP_EXECUTION_CONTEXT PRIMARY KEY (STEP_EXECUTION_ID)
);
GO

ALTER TABLE BATCH_STEP_EXECUTION_CONTEXT 
ADD CONSTRAINT STEP_EXEC_CTX_FK 
FOREIGN KEY (STEP_EXECUTION_ID) 
REFERENCES BATCH_STEP_EXECUTION(STEP_EXECUTION_ID);
GO

PRINT 'Table BATCH_STEP_EXECUTION_CONTEXT created.';
GO

-- 创建性能优化索引
CREATE INDEX IDX_JOB_EXEC_STATUS ON BATCH_JOB_EXECUTION(STATUS);
CREATE INDEX IDX_JOB_EXEC_CREATE_TIME ON BATCH_JOB_EXECUTION(CREATE_TIME);
CREATE INDEX IDX_STEP_EXEC_STATUS ON BATCH_STEP_EXECUTION(STATUS);
CREATE INDEX IDX_STEP_EXEC_CREATE_TIME ON BATCH_STEP_EXECUTION(CREATE_TIME);
GO

PRINT 'Spring Batch metadata tables and indexes created successfully!';
GO
