-- ===============================================================================================
-- Spring Batch Core Tables (SQL Server)
-- ===============================================================================================

IF OBJECT_ID('BATCH_STEP_EXECUTION_CONTEXT', 'U') IS NOT NULL DROP TABLE BATCH_STEP_EXECUTION_CONTEXT;
IF OBJECT_ID('BATCH_JOB_EXECUTION_CONTEXT', 'U') IS NOT NULL DROP TABLE BATCH_JOB_EXECUTION_CONTEXT;
IF OBJECT_ID('BATCH_STEP_EXECUTION', 'U') IS NOT NULL DROP TABLE BATCH_STEP_EXECUTION;
IF OBJECT_ID('BATCH_JOB_EXECUTION_PARAMS', 'U') IS NOT NULL DROP TABLE BATCH_JOB_EXECUTION_PARAMS;
IF OBJECT_ID('BATCH_JOB_EXECUTION', 'U') IS NOT NULL DROP TABLE BATCH_JOB_EXECUTION;
IF OBJECT_ID('BATCH_JOB_INSTANCE', 'U') IS NOT NULL DROP TABLE BATCH_JOB_INSTANCE;

IF OBJECT_ID('BATCH_STEP_EXECUTION_SEQ', 'SO') IS NOT NULL DROP SEQUENCE BATCH_STEP_EXECUTION_SEQ;
IF OBJECT_ID('BATCH_JOB_EXECUTION_SEQ', 'SO') IS NOT NULL DROP SEQUENCE BATCH_JOB_EXECUTION_SEQ;
IF OBJECT_ID('BATCH_JOB_SEQ', 'SO') IS NOT NULL DROP SEQUENCE BATCH_JOB_SEQ;

CREATE TABLE BATCH_JOB_INSTANCE  (
	JOB_INSTANCE_ID BIGINT  NOT NULL PRIMARY KEY ,
	VERSION BIGINT ,
	JOB_NAME NVARCHAR(100) NOT NULL,
	JOB_KEY NVARCHAR(32) NOT NULL,
	CONSTRAINT JOB_INST_UN UNIQUE (JOB_NAME, JOB_KEY)
) ;

CREATE TABLE BATCH_JOB_EXECUTION  (
	JOB_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY ,
	VERSION BIGINT  ,
	JOB_INSTANCE_ID BIGINT NOT NULL,
	CREATE_TIME DATETIME NOT NULL,
	START_TIME DATETIME DEFAULT NULL ,
	END_TIME DATETIME DEFAULT NULL ,
	STATUS NVARCHAR(10) ,
	EXIT_CODE NVARCHAR(2500) ,
	EXIT_MESSAGE NVARCHAR(2500) ,
	LAST_UPDATED DATETIME,
	CONSTRAINT JOB_INST_EXEC_FK FOREIGN KEY (JOB_INSTANCE_ID)
	REFERENCES BATCH_JOB_INSTANCE (JOB_INSTANCE_ID)
) ;

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS  (
	JOB_EXECUTION_ID BIGINT NOT NULL ,
	PARAMETER_NAME NVARCHAR(100) NOT NULL ,
	PARAMETER_TYPE NVARCHAR(100) NOT NULL ,
	PARAMETER_VALUE NVARCHAR(2500) ,
	IDENTIFYING CHAR(1) NOT NULL ,
	CONSTRAINT JOB_EXEC_PARAMS_FK FOREIGN KEY (JOB_EXECUTION_ID)
	REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
) ;

CREATE TABLE BATCH_STEP_EXECUTION  (
	STEP_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY ,
	VERSION BIGINT NOT NULL,
	STEP_NAME NVARCHAR(100) NOT NULL,
	JOB_EXECUTION_ID BIGINT NOT NULL,
	CREATE_TIME DATETIME NOT NULL,
	START_TIME DATETIME DEFAULT NULL ,
	END_TIME DATETIME DEFAULT NULL ,
	STATUS NVARCHAR(10) ,
	COMMIT_COUNT BIGINT ,
	READ_COUNT BIGINT ,
	FILTER_COUNT BIGINT ,
	WRITE_COUNT BIGINT ,
	READ_SKIP_COUNT BIGINT ,
	WRITE_SKIP_COUNT BIGINT ,
	PROCESS_SKIP_COUNT BIGINT ,
	ROLLBACK_COUNT BIGINT ,
	EXIT_CODE NVARCHAR(2500) ,
	EXIT_MESSAGE NVARCHAR(2500) ,
	LAST_UPDATED DATETIME,
	CONSTRAINT JOB_EXEC_STEP_FK FOREIGN KEY (JOB_EXECUTION_ID)
	REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
) ;

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT  (
	STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
	SHORT_CONTEXT NVARCHAR(2500) NOT NULL,
	SERIALIZED_CONTEXT NVARCHAR(MAX) ,
	CONSTRAINT STEP_EXEC_CTX_FK FOREIGN KEY (STEP_EXECUTION_ID)
	REFERENCES BATCH_STEP_EXECUTION (STEP_EXECUTION_ID)
) ;

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT  (
	JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
	SHORT_CONTEXT NVARCHAR(2500) NOT NULL,
	SERIALIZED_CONTEXT NVARCHAR(MAX) ,
	CONSTRAINT JOB_EXEC_CTX_FK FOREIGN KEY (JOB_EXECUTION_ID)
	REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
) ;

CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE BATCH_JOB_SEQ START WITH 1 INCREMENT BY 1;

-- ===============================================================================================
-- Demo Business Tables
-- ===============================================================================================

IF OBJECT_ID('DEMO_USER', 'U') IS NOT NULL DROP TABLE DEMO_USER;

CREATE TABLE DEMO_USER (
    ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    USERNAME NVARCHAR(100) NOT NULL,
    EMAIL NVARCHAR(100),
    STATUS NVARCHAR(20) DEFAULT 'ACTIVE',
    CREATE_TIME DATETIME DEFAULT GETDATE(),
    UPDATE_TIME DATETIME DEFAULT GETDATE()
);

-- Add comments for documentation
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Demo User Table for Batch Processing', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'DEMO_USER';
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'User Login Name', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'DEMO_USER', @level2type = N'COLUMN', @level2name = N'USERNAME';
