-- =============================================
-- BatchWeaver SQL Server 2022 初始化脚本
-- =============================================

-- 1. 创建数据库
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'BatchWeaverDB')
BEGIN
    CREATE DATABASE BatchWeaverDB;
    PRINT 'Database BatchWeaverDB created successfully.';
END
ELSE
BEGIN
    PRINT 'Database BatchWeaverDB already exists.';
END
GO

-- 2. 使用数据库
USE BatchWeaverDB;
GO

-- 3. 创建业务表
IF OBJECT_ID('USER_DATA', 'U') IS NOT NULL
BEGIN
    DROP TABLE USER_DATA;
    PRINT 'Table USER_DATA dropped.';
END
GO

CREATE TABLE USER_DATA (
    ID BIGINT IDENTITY(1,1) NOT NULL,
    NAME NVARCHAR(100),
    EMAIL NVARCHAR(100),
    CREATED_DATE DATETIME2 DEFAULT GETDATE(),
    CONSTRAINT PK_USER_DATA PRIMARY KEY (ID)
);
GO

PRINT 'Table USER_DATA created successfully.';
GO

-- 4. 创建索引
CREATE INDEX IX_USER_DATA_EMAIL ON USER_DATA(EMAIL);
CREATE INDEX IX_USER_DATA_NAME ON USER_DATA(NAME);
GO

PRINT 'Indexes created successfully.';
GO

-- 5. 插入测试数据（可选）
INSERT INTO USER_DATA (NAME, EMAIL) VALUES 
    (N'Alice', N'alice@example.com'),
    (N'Bob', N'bob@example.com'),
    (N'Charlie', N'charlie@example.com');
GO

PRINT 'Test data inserted successfully.';
GO

-- 6. 创建 Spring Batch 元数据表
PRINT 'Creating Spring Batch metadata tables...';
GO

-- BATCH_JOB_INSTANCE
IF OBJECT_ID('BATCH_JOB_INSTANCE', 'U') IS NOT NULL
    DROP TABLE BATCH_JOB_INSTANCE;
GO

CREATE TABLE BATCH_JOB_INSTANCE (
    JOB_INSTANCE_ID BIGINT IDENTITY(1,1) NOT NULL,
    VERSION BIGINT,
    JOB_NAME NVARCHAR(100) NOT NULL,
    JOB_KEY NVARCHAR(32) NOT NULL,
    CONSTRAINT PK_BATCH_JOB_INSTANCE PRIMARY KEY (JOB_INSTANCE_ID)
);
GO

CREATE UNIQUE INDEX JOB_INST_UN ON BATCH_JOB_INSTANCE (JOB_NAME, JOB_KEY);
GO

-- BATCH_JOB_EXECUTION
IF OBJECT_ID('BATCH_JOB_EXECUTION', 'U') IS NOT NULL
    DROP TABLE BATCH_JOB_EXECUTION;
GO

CREATE TABLE BATCH_JOB_EXECUTION (
    JOB_EXECUTION_ID BIGINT IDENTITY(1,1) NOT NULL,
    VERSION BIGINT,
    JOB_INSTANCE_ID BIGINT NOT NULL,
    CREATE_TIME DATETIME2 NOT NULL,
    START_TIME DATETIME2,
    END_TIME DATETIME2,
    STATUS NVARCHAR(10),
    EXIT_CODE NVARCHAR(2500),
    EXIT_MESSAGE NVARCHAR(2500),
    LAST_UPDATED DATETIME2,
    CONSTRAINT PK_BATCH_JOB_EXECUTION PRIMARY KEY (JOB_EXECUTION_ID)
);
GO

ALTER TABLE BATCH_JOB_EXECUTION 
ADD CONSTRAINT JOB_INST_EXEC_FK 
FOREIGN KEY (JOB_INSTANCE_ID) 
REFERENCES BATCH_JOB_INSTANCE(JOB_INSTANCE_ID);
GO

-- BATCH_JOB_EXECUTION_PARAMS
IF OBJECT_ID('BATCH_JOB_EXECUTION_PARAMS', 'U') IS NOT NULL
    DROP TABLE BATCH_JOB_EXECUTION_PARAMS;
GO

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS (
    JOB_EXECUTION_ID BIGINT NOT NULL,
    PARAMETER_NAME NVARCHAR(100) NOT NULL,
    PARAMETER_TYPE NVARCHAR(100) NOT NULL,
    PARAMETER_VALUE NVARCHAR(2500),
    IDENTIFYING CHAR(1) NOT NULL,
    CONSTRAINT JOB_EXEC_PARAMS_FK 
    FOREIGN KEY (JOB_EXECUTION_ID) 
    REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);
GO

-- BATCH_STEP_EXECUTION
IF OBJECT_ID('BATCH_STEP_EXECUTION', 'U') IS NOT NULL
    DROP TABLE BATCH_STEP_EXECUTION;
GO

CREATE TABLE BATCH_STEP_EXECUTION (
    STEP_EXECUTION_ID BIGINT IDENTITY(1,1) NOT NULL,
    VERSION BIGINT NOT NULL,
    STEP_NAME NVARCHAR(100) NOT NULL,
    JOB_EXECUTION_ID BIGINT NOT NULL,
    CREATE_TIME DATETIME2 NOT NULL,
    START_TIME DATETIME2,
    END_TIME DATETIME2,
    STATUS NVARCHAR(10),
    COMMIT_COUNT BIGINT,
    READ_COUNT BIGINT,
    FILTER_COUNT BIGINT,
    WRITE_COUNT BIGINT,
    READ_SKIP_COUNT BIGINT,
    WRITE_SKIP_COUNT BIGINT,
    PROCESS_SKIP_COUNT BIGINT,
    ROLLBACK_COUNT BIGINT,
    EXIT_CODE NVARCHAR(2500),
    EXIT_MESSAGE NVARCHAR(2500),
    LAST_UPDATED DATETIME2,
    CONSTRAINT PK_BATCH_STEP_EXECUTION PRIMARY KEY (STEP_EXECUTION_ID)
);
GO

ALTER TABLE BATCH_STEP_EXECUTION 
ADD CONSTRAINT JOB_EXEC_STEP_FK 
FOREIGN KEY (JOB_EXECUTION_ID) 
REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID);
GO

-- BATCH_JOB_EXECUTION_CONTEXT
IF OBJECT_ID('BATCH_JOB_EXECUTION_CONTEXT', 'U') IS NOT NULL
    DROP TABLE BATCH_JOB_EXECUTION_CONTEXT;
GO

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT (
    JOB_EXECUTION_ID BIGINT NOT NULL,
    SHORT_CONTEXT NVARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT NVARCHAR(MAX),
    CONSTRAINT PK_BATCH_JOB_EXECUTION_CONTEXT PRIMARY KEY (JOB_EXECUTION_ID)
);
GO

ALTER TABLE BATCH_JOB_EXECUTION_CONTEXT 
ADD CONSTRAINT JOB_EXEC_CTX_FK 
FOREIGN KEY (JOB_EXECUTION_ID) 
REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID);
GO

-- BATCH_STEP_EXECUTION_CONTEXT
IF OBJECT_ID('BATCH_STEP_EXECUTION_CONTEXT', 'U') IS NOT NULL
    DROP TABLE BATCH_STEP_EXECUTION_CONTEXT;
GO

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT (
    STEP_EXECUTION_ID BIGINT NOT NULL,
    SHORT_CONTEXT NVARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT NVARCHAR(MAX),
    CONSTRAINT PK_BATCH_STEP_EXECUTION_CONTEXT PRIMARY KEY (STEP_EXECUTION_ID)
);
GO

ALTER TABLE BATCH_STEP_EXECUTION_CONTEXT 
ADD CONSTRAINT STEP_EXEC_CTX_FK 
FOREIGN KEY (STEP_EXECUTION_ID) 
REFERENCES BATCH_STEP_EXECUTION(STEP_EXECUTION_ID);
GO

-- 创建性能优化索引
CREATE INDEX IDX_JOB_EXEC_STATUS ON BATCH_JOB_EXECUTION(STATUS);
CREATE INDEX IDX_JOB_EXEC_CREATE_TIME ON BATCH_JOB_EXECUTION(CREATE_TIME);
CREATE INDEX IDX_STEP_EXEC_STATUS ON BATCH_STEP_EXECUTION(STATUS);
CREATE INDEX IDX_STEP_EXEC_CREATE_TIME ON BATCH_STEP_EXECUTION(CREATE_TIME);
GO

PRINT 'Spring Batch metadata tables created successfully!';
GO

-- 7. 验证所有表
PRINT 'Verifying all tables...';
GO

SELECT 
    TABLE_NAME,
    TABLE_TYPE
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_NAME IN ('USER_DATA', 'BATCH_JOB_INSTANCE', 'BATCH_JOB_EXECUTION', 
                     'BATCH_JOB_EXECUTION_PARAMS', 'BATCH_STEP_EXECUTION',
                     'BATCH_JOB_EXECUTION_CONTEXT', 'BATCH_STEP_EXECUTION_CONTEXT')
ORDER BY TABLE_NAME;
GO

SELECT COUNT(*) AS TotalRecords FROM USER_DATA;
GO

PRINT 'Initialization completed successfully!';
PRINT 'All business and Spring Batch metadata tables are ready.';
GO
